# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CoreControllGui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1396, 858)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_1)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 460, 511, 181))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_50.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget_2)
        self.widget.setStyleSheet("background-color: rgb(255, 237, 192);")
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 157))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_8.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_8.addWidget(self.radioButton_2)
        self.verticalLayout_18.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout_18.addLayout(self.horizontalLayout)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout_18.addWidget(self.textBrowser_3)
        self.horizontalLayout_24.addLayout(self.verticalLayout_18)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(50, 0))
        self.label_6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_11.addWidget(self.lineEdit_6)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(50, 0))
        self.label_7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_12.addWidget(self.lineEdit_5)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_16.addWidget(self.pushButton_3)
        self.progressBar_3 = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar_3.setProperty("value", 1)
        self.progressBar_3.setObjectName("progressBar_3")
        self.horizontalLayout_16.addWidget(self.progressBar_3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_24.addLayout(self.verticalLayout_10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_50.addWidget(self.widget)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab_1)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 150, 641, 261))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_2 = QtWidgets.QWidget(self.horizontalLayoutWidget_4)
        self.widget_2.setStyleSheet("background-color: rgb(255, 248, 207);")
        self.widget_2.setObjectName("widget_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.widget_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 601, 241))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_3.addWidget(self.label_25)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_9.addWidget(self.pushButton)
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget1)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_9.addWidget(self.textBrowser)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 0, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 0, 1, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout.addWidget(self.checkBox_9, 0, 2, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout.addWidget(self.checkBox_11, 0, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 1, 0, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 1, 1, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout.addWidget(self.checkBox_10, 1, 2, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout.addWidget(self.checkBox_12, 1, 3, 1, 1)
        self.horizontalLayout_14.addLayout(self.gridLayout)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_14.addWidget(self.pushButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_21.setFont(font)
        self.lineEdit_21.setStyleSheet("color: rgb(255, 0, 0);\n"
"")
        self.lineEdit_21.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.verticalLayout_3.addWidget(self.lineEdit_21)
        self.horizontalLayout_6.addWidget(self.widget_2)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_1)
        self.layoutWidget2.setGeometry(QtCore.QRect(110, 60, 326, 78))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.verticalLayout_2.addWidget(self.lineEdit_14)
        self.horizontalLayout_17.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_6.addWidget(self.pushButton_9)
        self.progressBar_1 = QtWidgets.QProgressBar(self.layoutWidget2)
        self.progressBar_1.setProperty("value", 0)
        self.progressBar_1.setObjectName("progressBar_1")
        self.verticalLayout_6.addWidget(self.progressBar_1)
        self.horizontalLayout_17.addLayout(self.verticalLayout_6)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.tab_1)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(690, 170, 511, 171))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.widget_3 = QtWidgets.QWidget(self.horizontalLayoutWidget_7)
        self.widget_3.setStyleSheet("background-color: rgb(199, 194, 255);")
        self.widget_3.setObjectName("widget_3")
        self.layoutWidget3 = QtWidgets.QWidget(self.widget_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 491, 148))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_19.addWidget(self.label_18)
        self.line_25 = QtWidgets.QFrame(self.layoutWidget3)
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.verticalLayout_19.addWidget(self.line_25)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_19.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_24.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 0, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_31.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 0, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_29.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 1, 0, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_20.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_2.addWidget(self.lineEdit_20, 1, 1, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_28.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_28.setFont(font)
        self.lineEdit_28.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_2.addWidget(self.lineEdit_28, 1, 2, 1, 1)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_36.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_36.setFont(font)
        self.lineEdit_36.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_2.addWidget(self.lineEdit_36, 1, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_30.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 2, 0, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_25.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_2.addWidget(self.lineEdit_25, 2, 1, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_33.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_33.setFont(font)
        self.lineEdit_33.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_2.addWidget(self.lineEdit_33, 2, 2, 1, 1)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_37.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_37.setFont(font)
        self.lineEdit_37.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout_2.addWidget(self.lineEdit_37, 2, 3, 1, 1)
        self.verticalLayout_19.addLayout(self.gridLayout_2)
        self.line_26 = QtWidgets.QFrame(self.layoutWidget3)
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.verticalLayout_19.addWidget(self.line_26)
        self.horizontalLayout_31.addWidget(self.widget_3)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_5)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 261, 741))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_49.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.widget_7 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_7.setStyleSheet("background-color: rgb(194, 227, 255);")
        self.widget_7.setObjectName("widget_7")
        self.layoutWidget4 = QtWidgets.QWidget(self.widget_7)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 20, 239, 577))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_10 = QtWidgets.QFrame(self.layoutWidget4)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout.addWidget(self.line_10)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setStyleSheet("color: rgb(255, 0, 0);\n"
"")
        self.lineEdit_22.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.verticalLayout.addWidget(self.lineEdit_22)
        self.line_11 = QtWidgets.QFrame(self.layoutWidget4)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout.addWidget(self.line_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_3 = QtWidgets.QRadioButton(self.layoutWidget4)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_5.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.layoutWidget4)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_5.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.layoutWidget4)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_5.addWidget(self.radioButton_5)
        self.horizontalLayout_13.addLayout(self.verticalLayout_5)
        self.pushButton_19 = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_13.addWidget(self.pushButton_19)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.verticalLayout.addWidget(self.lineEdit_15)
        self.line_12 = QtWidgets.QFrame(self.layoutWidget4)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout.addWidget(self.line_12)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.layoutWidget4)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_7.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget4)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_3.addWidget(self.lineEdit_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.label_39 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_67.addWidget(self.label_39)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_35.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.horizontalLayout_67.addWidget(self.lineEdit_35)
        self.verticalLayout.addLayout(self.horizontalLayout_67)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_10.addWidget(self.lineEdit_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout.addWidget(self.lineEdit_11)
        self.line = QtWidgets.QFrame(self.layoutWidget4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_17 = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_4.addWidget(self.pushButton_17)
        self.progressBar_10 = QtWidgets.QProgressBar(self.layoutWidget4)
        self.progressBar_10.setMaximumSize(QtCore.QSize(50, 16777215))
        self.progressBar_10.setProperty("value", 0)
        self.progressBar_10.setObjectName("progressBar_10")
        self.horizontalLayout_4.addWidget(self.progressBar_10)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_33.addLayout(self.verticalLayout)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_12.addWidget(self.label_23)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.verticalSlider_1 = QtWidgets.QSlider(self.layoutWidget4)
        self.verticalSlider_1.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_1.setObjectName("verticalSlider_1")
        self.horizontalLayout_32.addWidget(self.verticalSlider_1)
        self.verticalSlider_2 = QtWidgets.QSlider(self.layoutWidget4)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.horizontalLayout_32.addWidget(self.verticalSlider_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33.addLayout(self.verticalLayout_12)
        self.verticalLayout_16.addLayout(self.horizontalLayout_33)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_14.addWidget(self.label_22)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalSlider_1 = QtWidgets.QSlider(self.layoutWidget4)
        self.horizontalSlider_1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_1.setObjectName("horizontalSlider_1")
        self.verticalLayout_13.addWidget(self.horizontalSlider_1)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.layoutWidget4)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.verticalLayout_13.addWidget(self.horizontalSlider_2)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.verticalLayout_16.addLayout(self.verticalLayout_14)
        self.layoutWidget5 = QtWidgets.QWidget(self.widget_7)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 610, 123, 84))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget5)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_20.addWidget(self.checkBox_4)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_35.addWidget(self.label_32)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.horizontalLayout_35.addWidget(self.lineEdit_38)
        self.verticalLayout_20.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.radioButton_14 = QtWidgets.QRadioButton(self.layoutWidget5)
        self.radioButton_14.setObjectName("radioButton_14")
        self.horizontalLayout_34.addWidget(self.radioButton_14)
        self.radioButton_15 = QtWidgets.QRadioButton(self.layoutWidget5)
        self.radioButton_15.setObjectName("radioButton_15")
        self.horizontalLayout_34.addWidget(self.radioButton_15)
        self.verticalLayout_20.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_49.addWidget(self.widget_7)
        self.layoutWidget_6 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget_6.setGeometry(QtCore.QRect(290, 10, 901, 741))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.widget_16 = QtWidgets.QWidget(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_16.sizePolicy().hasHeightForWidth())
        self.widget_16.setSizePolicy(sizePolicy)
        self.widget_16.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_25.addWidget(self.widget_16)
        self.verticalLayout_27.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.widget_17 = QtWidgets.QWidget(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_17.sizePolicy().hasHeightForWidth())
        self.widget_17.setSizePolicy(sizePolicy)
        self.widget_17.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_56.addWidget(self.widget_17)
        self.verticalLayout_27.addLayout(self.horizontalLayout_56)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_6)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 201, 781))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_51.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.widget_5 = QtWidgets.QWidget(self.horizontalLayoutWidget_3)
        self.widget_5.setStyleSheet("background-color: rgb(221, 255, 202);")
        self.widget_5.setObjectName("widget_5")
        self.layoutWidget6 = QtWidgets.QWidget(self.widget_5)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 13, 181, 759))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget6)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_15.addWidget(self.pushButton_5)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.verticalLayout_15.addWidget(self.textBrowser_4)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget6)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_15.addWidget(self.line_5)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget6)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_39.addWidget(self.pushButton_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_39.addWidget(self.lineEdit_7)
        self.verticalLayout_15.addLayout(self.horizontalLayout_39)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget6)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_15.addWidget(self.line_6)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_10.setMinimumSize(QtCore.QSize(30, 0))
        self.label_10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_18.addWidget(self.label_10)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_18.addWidget(self.lineEdit_8)
        self.verticalLayout_15.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_11.setMinimumSize(QtCore.QSize(30, 0))
        self.label_11.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_19.addWidget(self.label_11)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_19.addWidget(self.lineEdit_9)
        self.verticalLayout_15.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_41 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_41.setMinimumSize(QtCore.QSize(30, 0))
        self.label_41.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_38.addWidget(self.label_41)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_41.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.horizontalLayout_38.addWidget(self.lineEdit_41)
        self.verticalLayout_15.addLayout(self.horizontalLayout_38)
        self.line_7 = QtWidgets.QFrame(self.layoutWidget6)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_15.addWidget(self.line_7)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_12.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_26.addWidget(self.label_12)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(25, 0))
        self.lineEdit_10.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_26.addWidget(self.lineEdit_10)
        self.verticalLayout_15.addLayout(self.horizontalLayout_26)
        self.line_8 = QtWidgets.QFrame(self.layoutWidget6)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_15.addWidget(self.line_8)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setStyleSheet("color: rgb(255, 0, 0);\n"
"")
        self.lineEdit_23.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.verticalLayout_15.addWidget(self.lineEdit_23)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.checkBox_13 = QtWidgets.QCheckBox(self.layoutWidget6)
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout_15.addWidget(self.checkBox_13)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget6)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_15.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget6)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_15.addWidget(self.checkBox_3)
        self.verticalLayout_15.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_33.setMinimumSize(QtCore.QSize(100, 0))
        self.label_33.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_61.addWidget(self.label_33)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_30.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_30.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.horizontalLayout_61.addWidget(self.lineEdit_30)
        self.verticalLayout_15.addLayout(self.horizontalLayout_61)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.radioButton_12 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioButton_12.setObjectName("radioButton_12")
        self.verticalLayout_17.addWidget(self.radioButton_12)
        self.radioButton_13 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioButton_13.setObjectName("radioButton_13")
        self.verticalLayout_17.addWidget(self.radioButton_13)
        self.radioButton_16 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioButton_16.setObjectName("radioButton_16")
        self.verticalLayout_17.addWidget(self.radioButton_16)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_36.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_36.addWidget(self.label_36)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_39.setMaximumSize(QtCore.QSize(42, 16777215))
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.horizontalLayout_36.addWidget(self.lineEdit_39)
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget6)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_36.addWidget(self.checkBox_5)
        self.verticalLayout_17.addLayout(self.horizontalLayout_36)
        self.verticalLayout_15.addLayout(self.verticalLayout_17)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget6)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_15.addWidget(self.pushButton_7)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout_15.addWidget(self.lineEdit_16)
        self.line_13 = QtWidgets.QFrame(self.layoutWidget6)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_15.addWidget(self.line_13)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_15.addWidget(self.label_14)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_15.addWidget(self.lineEdit_12)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget6)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_15.addWidget(self.line_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget6)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_5.addWidget(self.pushButton_8)
        self.progressBar_8 = QtWidgets.QProgressBar(self.layoutWidget6)
        self.progressBar_8.setProperty("value", 0)
        self.progressBar_8.setObjectName("progressBar_8")
        self.horizontalLayout_5.addWidget(self.progressBar_8)
        self.verticalLayout_15.addLayout(self.horizontalLayout_5)
        self.line_9 = QtWidgets.QFrame(self.layoutWidget6)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_15.addWidget(self.line_9)
        self.horizontalLayout_51.addWidget(self.widget_5)
        self.layoutWidget_5 = QtWidgets.QWidget(self.tab_6)
        self.layoutWidget_5.setGeometry(QtCore.QRect(230, 20, 981, 761))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.widget_14 = QtWidgets.QWidget(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy)
        self.widget_14.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_22.addWidget(self.widget_14)
        self.verticalLayout_26.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.widget_15 = QtWidgets.QWidget(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_15.sizePolicy().hasHeightForWidth())
        self.widget_15.setSizePolicy(sizePolicy)
        self.widget_15.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_52.addWidget(self.widget_15)
        self.verticalLayout_26.addLayout(self.horizontalLayout_52)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 241, 781))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_59.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.widget_13 = QtWidgets.QWidget(self.horizontalLayoutWidget_5)
        self.widget_13.setStyleSheet("background-color: rgb(239, 219, 255);")
        self.widget_13.setObjectName("widget_13")
        self.layoutWidget_2 = QtWidgets.QWidget(self.widget_13)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 221, 750))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.line_17 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.verticalLayout_7.addWidget(self.line_17)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_29.setFont(font)
        self.lineEdit_29.setStyleSheet("color: rgb(255, 0, 0);\n"
"")
        self.lineEdit_29.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.verticalLayout_7.addWidget(self.lineEdit_29)
        self.line_18 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.verticalLayout_7.addWidget(self.line_18)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_7.addWidget(self.label_37)
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_62.addWidget(self.label_34)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_31.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_31.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.horizontalLayout_62.addWidget(self.lineEdit_31)
        self.verticalLayout_7.addLayout(self.horizontalLayout_62)
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_63.addWidget(self.label_35)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_32.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.horizontalLayout_63.addWidget(self.lineEdit_32)
        self.verticalLayout_7.addLayout(self.horizontalLayout_63)
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_66.addWidget(self.label_38)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_34.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.horizontalLayout_66.addWidget(self.lineEdit_34)
        self.verticalLayout_7.addLayout(self.horizontalLayout_66)
        self.line_19 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.verticalLayout_7.addWidget(self.line_19)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_42 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_3.addWidget(self.label_42, 0, 1, 1, 1)
        self.radioButton_9 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radioButton_9.setObjectName("radioButton_9")
        self.gridLayout_3.addWidget(self.radioButton_9, 1, 0, 1, 1)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_42.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout_3.addWidget(self.lineEdit_42, 1, 1, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radioButton_10.setObjectName("radioButton_10")
        self.gridLayout_3.addWidget(self.radioButton_10, 2, 0, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_43.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout_3.addWidget(self.lineEdit_43, 2, 1, 1, 1)
        self.radioButton_11 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radioButton_11.setObjectName("radioButton_11")
        self.gridLayout_3.addWidget(self.radioButton_11, 3, 0, 1, 1)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_44.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout_3.addWidget(self.lineEdit_44, 3, 1, 1, 1)
        self.horizontalLayout_40.addLayout(self.gridLayout_3)
        self.pushButton_21 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_21.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_40.addWidget(self.pushButton_21)
        self.verticalLayout_7.addLayout(self.horizontalLayout_40)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout_7.addWidget(self.lineEdit_17)
        self.line_21 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.verticalLayout_7.addWidget(self.line_21)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_7.addWidget(self.label_15)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayout_7.addWidget(self.lineEdit_13)
        self.line_14 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_7.addWidget(self.line_14)
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.pushButton_22 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_65.addWidget(self.pushButton_22)
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_11.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_65.addWidget(self.pushButton_11)
        self.progressBar_12 = QtWidgets.QProgressBar(self.layoutWidget_2)
        self.progressBar_12.setMaximumSize(QtCore.QSize(50, 16777215))
        self.progressBar_12.setProperty("value", 0)
        self.progressBar_12.setObjectName("progressBar_12")
        self.horizontalLayout_65.addWidget(self.progressBar_12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_65)
        self.widget_9 = QtWidgets.QWidget(self.layoutWidget_2)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 250))
        self.widget_9.setObjectName("widget_9")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget_9)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 0, 201, 241))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_7.addWidget(self.widget_9)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_12.setMaximumSize(QtCore.QSize(100, 20))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_37.addWidget(self.pushButton_12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_59.addWidget(self.widget_13)
        self.layoutWidget7 = QtWidgets.QWidget(self.tab)
        self.layoutWidget7.setGeometry(QtCore.QRect(263, 13, 961, 771))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_4 = QtWidgets.QWidget(self.layoutWidget7)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_8.addWidget(self.widget_4)
        self.widget_18 = QtWidgets.QWidget(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_18.sizePolicy().hasHeightForWidth())
        self.widget_18.setSizePolicy(sizePolicy)
        self.widget_18.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_8.addWidget(self.widget_18)
        self.widget_6 = QtWidgets.QWidget(self.layoutWidget7)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_8.addWidget(self.widget_6)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 201, 741))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_53.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.widget_8 = QtWidgets.QWidget(self.horizontalLayoutWidget_6)
        self.widget_8.setStyleSheet("background-color: rgb(194, 227, 255);")
        self.widget_8.setObjectName("widget_8")
        self.layoutWidget_3 = QtWidgets.QWidget(self.widget_8)
        self.layoutWidget_3.setGeometry(QtCore.QRect(15, 12, 171, 550))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.line_15 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_9.addWidget(self.line_15)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_24.setFont(font)
        self.lineEdit_24.setStyleSheet("color: rgb(255, 0, 0);\n"
"")
        self.lineEdit_24.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.verticalLayout_9.addWidget(self.lineEdit_24)
        self.line_16 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_9.addWidget(self.line_16)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_9.addWidget(self.pushButton_10)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.radioButton_6 = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_11.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_11.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_11.addWidget(self.radioButton_8)
        self.horizontalLayout_21.addLayout(self.verticalLayout_11)
        self.pushButton_20 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_21.addWidget(self.pushButton_20)
        self.verticalLayout_9.addLayout(self.horizontalLayout_21)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.verticalLayout_9.addWidget(self.lineEdit_18)
        self.line_20 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.verticalLayout_9.addWidget(self.line_20)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_17.setMinimumSize(QtCore.QSize(100, 0))
        self.label_17.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_23.addWidget(self.label_17)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_19.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_19.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_23.addWidget(self.lineEdit_19)
        self.verticalLayout_9.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_40.setMinimumSize(QtCore.QSize(100, 0))
        self.label_40.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_27.addWidget(self.label_40)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_46.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_46.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.horizontalLayout_27.addWidget(self.lineEdit_46)
        self.verticalLayout_9.addLayout(self.horizontalLayout_27)
        self.line_23 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.verticalLayout_9.addWidget(self.line_23)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_21.addWidget(self.pushButton_13)
        self.verticalLayout_9.addLayout(self.verticalLayout_21)
        self.line_22 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.verticalLayout_9.addWidget(self.line_22)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_21.setObjectName("label_21")
        self.verticalLayout_9.addWidget(self.label_21)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.verticalLayout_9.addWidget(self.lineEdit_27)
        self.line_24 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.verticalLayout_9.addWidget(self.line_24)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.pushButton_18 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_30.addWidget(self.pushButton_18)
        self.progressBar_11 = QtWidgets.QProgressBar(self.layoutWidget_3)
        self.progressBar_11.setMaximumSize(QtCore.QSize(50, 16777215))
        self.progressBar_11.setProperty("value", 0)
        self.progressBar_11.setObjectName("progressBar_11")
        self.horizontalLayout_30.addWidget(self.progressBar_11)
        self.verticalLayout_9.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_53.addWidget(self.widget_8)
        self.widget1 = QtWidgets.QWidget(self.tab_2)
        self.widget1.setGeometry(QtCore.QRect(241, 21, 1111, 771))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.widget_10 = QtWidgets.QWidget(self.widget1)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_22.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.widget1)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_22.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.widget1)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_22.addWidget(self.widget_12)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_20.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_27.setText(_translate("MainWindow", "GAIN"))
        self.radioButton.setText(_translate("MainWindow", "Profile 1"))
        self.radioButton_2.setText(_translate("MainWindow", "Profile 2"))
        self.pushButton_4.setText(_translate("MainWindow", "Read"))
        self.label_5.setText(_translate("MainWindow", "Gain values"))
        self.label_6.setText(_translate("MainWindow", "Gain"))
        self.label_9.setText(_translate("MainWindow", "range 1..6"))
        self.label_7.setText(_translate("MainWindow", "Offset"))
        self.label_8.setText(_translate("MainWindow", "range -0.3..0.3V"))
        self.pushButton_3.setText(_translate("MainWindow", "Set"))
        self.label_25.setText(_translate("MainWindow", "PROFILES"))
        self.pushButton.setText(_translate("MainWindow", "Read Profiles"))
        self.label_26.setText(_translate("MainWindow", "Profile 1"))
        self.checkBox_7.setText(_translate("MainWindow", "532"))
        self.checkBox_9.setText(_translate("MainWindow", "785"))
        self.checkBox_11.setText(_translate("MainWindow", "1064"))
        self.label_28.setText(_translate("MainWindow", "Profile 2"))
        self.checkBox_8.setText(_translate("MainWindow", "532"))
        self.checkBox_10.setText(_translate("MainWindow", "785"))
        self.checkBox_12.setText(_translate("MainWindow", "1064"))
        self.pushButton_2.setText(_translate("MainWindow", "Set Profiles"))
        self.lineEdit_21.setText(_translate("MainWindow", "Profiles not assigned!"))
        self.label_16.setText(_translate("MainWindow", "IP"))
        self.lineEdit_14.setText(_translate("MainWindow", "10.131.51."))
        self.pushButton_9.setText(_translate("MainWindow", "Connect"))
        self.label_18.setText(_translate("MainWindow", "Set Laser Values"))
        self.label_19.setText(_translate("MainWindow", "532"))
        self.label_24.setText(_translate("MainWindow", "785"))
        self.label_31.setText(_translate("MainWindow", "1064"))
        self.label_29.setText(_translate("MainWindow", "%"))
        self.lineEdit_20.setText(_translate("MainWindow", "100"))
        self.lineEdit_28.setText(_translate("MainWindow", "100"))
        self.lineEdit_36.setText(_translate("MainWindow", "100"))
        self.label_30.setText(_translate("MainWindow", "mW"))
        self.lineEdit_25.setText(_translate("MainWindow", "50"))
        self.lineEdit_33.setText(_translate("MainWindow", "450"))
        self.lineEdit_37.setText(_translate("MainWindow", "450"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Settings"))
        self.lineEdit_22.setText(_translate("MainWindow", "Profiles not assigned!"))
        self.radioButton_3.setText(_translate("MainWindow", "532"))
        self.radioButton_4.setText(_translate("MainWindow", "785"))
        self.radioButton_5.setText(_translate("MainWindow", "1064"))
        self.pushButton_19.setText(_translate("MainWindow", "Capture"))
        self.label.setText(_translate("MainWindow", "IntegrationTime"))
        self.lineEdit.setText(_translate("MainWindow", "2"))
        self.checkBox.setText(_translate("MainWindow", "Ramp IntegrationTime"))
        self.label_3.setText(_translate("MainWindow", "from [s]"))
        self.label_4.setText(_translate("MainWindow", "to [s]"))
        self.label_39.setText(_translate("MainWindow", "step [s]"))
        self.label_2.setText(_translate("MainWindow", "Runs"))
        self.lineEdit_2.setText(_translate("MainWindow", "1"))
        self.label_13.setText(_translate("MainWindow", "File Info"))
        self.pushButton_17.setText(_translate("MainWindow", "Save Plot"))
        self.label_23.setText(_translate("MainWindow", "y"))
        self.label_22.setText(_translate("MainWindow", "x"))
        self.checkBox_4.setText(_translate("MainWindow", "show Baseline"))
        self.label_32.setText(_translate("MainWindow", "order"))
        self.lineEdit_38.setText(_translate("MainWindow", "1"))
        self.radioButton_14.setText(_translate("MainWindow", "Cylo"))
        self.radioButton_15.setText(_translate("MainWindow", "Benzo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "STDs"))
        self.pushButton_5.setText(_translate("MainWindow", " Call Stage values"))
        self.pushButton_6.setText(_translate("MainWindow", "move to:"))
        self.label_10.setText(_translate("MainWindow", "Start [mm]"))
        self.label_11.setText(_translate("MainWindow", "End  [mm]"))
        self.label_41.setText(_translate("MainWindow", "Step  [mm]"))
        self.lineEdit_41.setText(_translate("MainWindow", "0.1"))
        self.label_12.setText(_translate("MainWindow", "Iterations"))
        self.lineEdit_10.setText(_translate("MainWindow", "5"))
        self.lineEdit_23.setText(_translate("MainWindow", "Profiles not assigned!"))
        self.checkBox_13.setText(_translate("MainWindow", "532"))
        self.checkBox_2.setText(_translate("MainWindow", "785"))
        self.checkBox_3.setText(_translate("MainWindow", "1064"))
        self.label_33.setText(_translate("MainWindow", "IntegrationTime"))
        self.lineEdit_30.setText(_translate("MainWindow", "2"))
        self.radioButton_12.setText(_translate("MainWindow", "Cyclohexane"))
        self.radioButton_13.setText(_translate("MainWindow", "Polysterene"))
        self.radioButton_16.setText(_translate("MainWindow", "SRM 532"))
        self.label_36.setText(_translate("MainWindow", "order"))
        self.lineEdit_39.setText(_translate("MainWindow", "1"))
        self.checkBox_5.setText(_translate("MainWindow", "old fit"))
        self.pushButton_7.setText(_translate("MainWindow", "Move and Measure"))
        self.label_14.setText(_translate("MainWindow", "File Info"))
        self.pushButton_8.setText(_translate("MainWindow", "Save Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Stage"))
        self.lineEdit_29.setText(_translate("MainWindow", "Profiles not assigned!"))
        self.label_37.setText(_translate("MainWindow", "Ramp IntegrationTime"))
        self.label_34.setText(_translate("MainWindow", "from [s]"))
        self.label_35.setText(_translate("MainWindow", "to [s]"))
        self.label_38.setText(_translate("MainWindow", "step [s]"))
        self.label_42.setText(_translate("MainWindow", "step"))
        self.radioButton_9.setText(_translate("MainWindow", "532"))
        self.lineEdit_42.setText(_translate("MainWindow", "50"))
        self.radioButton_10.setText(_translate("MainWindow", "785"))
        self.lineEdit_43.setText(_translate("MainWindow", "50"))
        self.radioButton_11.setText(_translate("MainWindow", "1064"))
        self.lineEdit_44.setText(_translate("MainWindow", "5"))
        self.pushButton_21.setText(_translate("MainWindow", "Capture"))
        self.label_15.setText(_translate("MainWindow", "File Info"))
        self.pushButton_22.setText(_translate("MainWindow", "Save Plot"))
        self.pushButton_11.setText(_translate("MainWindow", "Grab"))
        self.pushButton_12.setText(_translate("MainWindow", "load File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "DetLin"))
        self.lineEdit_24.setText(_translate("MainWindow", "Profiles not assigned!"))
        self.pushButton_10.setText(_translate("MainWindow", "Connect OSA"))
        self.radioButton_6.setText(_translate("MainWindow", "532"))
        self.radioButton_7.setText(_translate("MainWindow", "785"))
        self.radioButton_8.setText(_translate("MainWindow", "1064"))
        self.pushButton_20.setText(_translate("MainWindow", "Capture"))
        self.label_17.setText(_translate("MainWindow", "Iterations"))
        self.lineEdit_19.setText(_translate("MainWindow", "1"))
        self.label_40.setText(_translate("MainWindow", "Break [min]"))
        self.lineEdit_46.setText(_translate("MainWindow", "0.1"))
        self.pushButton_13.setText(_translate("MainWindow", "Load FileFolder"))
        self.label_21.setText(_translate("MainWindow", "File Info"))
        self.pushButton_18.setText(_translate("MainWindow", "Save Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "OSA"))

